repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Linter
        entry: ruff check
        language: system
        types: [python]
        pass_filenames: true
      - id: ty-check
        name: Type Check
        entry: ty check
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff-format
        name: Formatter
        entry: ruff format
        language: system
        types: [python]
        pass_filenames: true
      # - id: pytest
      #   name: Unit Tests
      #   entry: bash -c 'PYTHONPATH=/Users/daniel/Source/airtable-formula-helper python -m pytest /Users/daniel/Source/airtable-formula-helper/tests/ -v' || (echo "Unit tests failed"; exit 1)
      #   language: system
      #   pass_filenames: false
      #   always_run: true
